### ISSUE TITLE
[Question] Can reuse same terminal.

### ISSUE THREAD

**Issue by dimas-cyriaco** [David-Kunz/jester#8]
Is there a way to use the same terminal used in the last test run, if it's still open?

Thanks for the great plugin!

**Comment by David-Kunz** [comment]
Hi @dimas-cyriaco ,

Thanks for this great feature request, you're absolutely right, the last terminal should be reused. Otherwise there are way too many terminals open (if not managed manually).

I changed the default behaviour, now the last terminal is used: https://github.com/David-Kunz/jester/commit/870f072bf322a5a895028679955025f6b4aef84f

Would you mind trying it out yourself?

Thanks a lot for this suggestion and best regards,
David

**Comment by dimas-cyriaco** [comment]
@David-Kunz It works perfectly. Thanks a lot!!
